### Importing Libaries:

In [1]:
import pandas as pd
import plotly.express as px
import seaborn as sns

### Loading the dataset:

In [5]:
df = pd.read_csv(r"C:\Users\RGB LAPTOPS\Documents\imp\AI 6 months Mentorship\university_hierarchy.csv")
df.head()

   ID                               Name        Type  Parent_ID  Level
0   1                  Global University  University        NaN      1
1   2             Faculty of Engineering     Faculty        1.0      2
2   3                Faculty of Business     Faculty        1.0      2
3   4        Computer Science Department  Department        2.0      3
4   5  Electrical Engineering Department  Department        2.0      3

## Sunburst Plot:

In [9]:
fig = px.sunburst(df, path=['Type', 'Name'], color='Type')
fig.show()

## Animated Plot:

>importing an inbuilt dataset from plotly:

In [10]:
df1 = px.data.gapminder()
df1.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [14]:
fig = px.scatter(df1, x='gdpPercap', y='lifeExp', color='continent', size='pop',animation_frame='year',log_x=True,size_max=55,range_x=[100,100000],range_y=[5,100])
fig.show()

## Animated Plot on dataset created from scratch:

In [ ]:
fig1 = px.scatter(
    df,
    x='Parent_ID',
    y='Level',
    color='Type',
    size='Level',
    hover_name='Name',
    animation_frame='Type',
    animation_group='ID',
    size_max=55,
    range_x=[0, 11],
    range_y=[0.5, 5.5],
    title='University Hierarchy Animation',
    labels={'Parent_ID': 'Parent ID', 'Level': 'Hierarchy Level'}
)
fig1.update_traces(marker=dict(opacity=0.85, line=dict(width=1, color='DarkSlateGrey')))
fig1.update_layout(plot_bgcolor='whitesmoke', transition={'duration': 600})
fig1.show()